### ISSUE TITLE
Import element remaining in flattening XSDL

### ISSUE THREAD

**Issue by chvilalukas** [php-soap/wsdl#21]
### Bug Report

If there is an **import** element in the XSDL, this element remains in flattening results. If I put the results into SoapClient, it will report an error:
`SoapFault exception: [WSDL] SOAP-ERROR: Parsing Schema: unexpected <import> in schema`

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.9.0

#### Summary

When WSDL look like
```xml
<xsd:schema ...>
    <xsd:import schemaLocation="TestSoap.xsd" namespace="http://www.test.com/xsd/xxxx"/>

    XSD CONTENT

</xsd:schema>	
```

#### Current behaviour

The flattening process results is:
```xml
<xsd:schema ...>
    <import namespace="http://www.test.com/xsd/xxxx"/>

    IMPORTED XSD CONTENT

    XSD CONTENT

</definitiions>	
```

#### Expected behaviour

```xml
<xsd:schema ...>
    IMPORTED XSD CONTENT

    XSD CONTENT

</definitiions>	
```

**Comment by veewee** [comment]
Hi @chvilalukas 

Can you link to the failing WSDL in this issue?
Alternatively, upload a zip of all the separate files?

**Comment by chvilalukas** [comment]
Hi @veewee
Is it possible to send you the failing XSDL privately? It is an insurance company XSDL and therefore I cannot put it here publicly.

**Comment by veewee** [comment]
Hello,

You can send it to toonverwerft at Gmail.com

**Comment by chvilalukas** [comment]
Thank you, you should have it in the mail

**Comment by veewee** [comment]
Thanks, will take a look at it once I'm back from vacation.

**Comment by veewee** [comment]
Hello @chvilalukas,

I'm not sure this is a bug from our end or from PHP's end to be honest:

When I validate the flattened WSDL, I see some notices:

```
	356:76	schema.xsd	s4s-elt-invalid-content.3: Elements of type 'import' cannot appear after declarations as children of a element.
	382:76	schema.xsd	s4s-elt-invalid-content.3: Elements of type 'import' cannot appear after declarations as children of a element.
	413:76	schema.xsd	s4s-elt-invalid-content.3: Elements of type 'import' cannot appear after declarations as children of a element.
	443:76	schema.xsd	s4s-elt-invalid-content.3: Elements of type 'import' cannot appear after declarations as children of a element.
```

Since they are just warnings which are not really enforced by XSD / XML itself they should not really be blocking. 
However, when PHP parses a XSD schema, it somehow expects those elements to be the first elements of a schema and continues parsing it's types next. Which results in an error because the import node is not really valid at that moment for PHPs parser.

See https://github.com/php/php-src/blob/96840072fc2f2214fefa73583f28e02c5d300ddc/ext/soap/php_schema.c#L166-L297 


BUT ...

When you import the flattened xml into SOAP-UI, there is no error whatsoever and the WSDL just loads. Therefore I think the issue is more in how PHP parses the WSDL than the format of the WSDL.

Allthough it might make more sense to rearrange the imports to appear first after flattening so that the validation warning also disappears.

I can't really find  much details about the rules on where to place the imports.


However, in this codebase I could add something like this:

```diff
diff --git a/src/Xml/Configurator/FlattenXsdImports.php b/src/Xml/Configurator/FlattenXsdImports.php
index af52a5d..25f10ff 100644
--- a/src/Xml/Configurator/FlattenXsdImports.php
+++ b/src/Xml/Configurator/FlattenXsdImports.php
@@ -65,6 +65,8 @@ final class FlattenXsdImports implements Configurator
             }
         }

+        $this->ensureImportStatementsArePlacedFirst($xml);
+
         return $document;
     }

@@ -219,4 +221,23 @@ final class FlattenXsdImports implements Configurator

         $target->setAttribute('xmlns', $source->getAttribute('xmlns'));
     }
+
+    /**
+     * Fixes WARNING : s4s-elt-invalid-content.3: Elements of type 'import' cannot appear after declarations as children of a element.
+     * PHP's SOAP-client reads imports before reading other elements which results in failures.
+     * This results in a failure like "[WSDL] SOAP-ERROR: Parsing Schema: unexpected <import> in schema"
+     * when the import is not the first child of the parent's schema element.
+     */
+    private function ensureImportStatementsArePlacedFirst(Document $xml): void
+    {
+        $xpath = $xml->xpath(new WsdlPreset($xml));
+        $xpath
+            ->query('//schema:import')
+            ->expectAllOfType(DOMElement::class)
+            ->forEach(static function (DOMElement $import) {
+                $parentSchema = assert_element($import->parentNode);
+                $parentSchema->prepend($import);
+            });
+    }
+
 }
```


This seems to do the trick on the WSDL you provided. But I'm not sure its the best approach to take since I can't find much details about the rules.
I'll leave this here and let it sink in to see how to go forward.


In the meantime, you can try one of the following:

* re-sort the `<xsd:import />` elements to apear as the first schema elements manually
*  use https://github.com/phpro/soap-client/releases/tag/4.0.0-alpha1 which skips SoapClient alltogether.

**Comment by chvilalukas** [comment]
Hello @veewee

I can confirm that the fix is working. We use a lot of different SOAP APIs and it works fine with the ones I've tested it on.

I put the class with this modification into our code and used it instead of the original class using the **autoload** composer.json element. This seems to be a workable solution until you put the fix for the problem in your repository. I'll try to put it on our deployment for test and then on production and see if it doesn't cause some other problem.

**Comment by veewee** [comment]
Hello @chvilalukas 

It turns out this is described in the XSD spec after all.
So I decided to merge it in. It's tagged as 1.10 and there for you to use.

Have fun!
